name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: zerotier/ZeroTierOne
          ref: 1.6.6
          path: zerotier
      - name: Run a multi-line script
        run: |
          nproc
          cd zerotier
          make -j`nproc`
          
