name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo ------------------------------------
          ifconfig -a
          echo ------------------------------------
          hostname -A 
          echo ------------------------------------
          hostname -d
          echo ------------------------------------
          hostname -f
          echo ------------------------------------
