name: CI
on:
  workflow_dispatch:
jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
      - name: Cache ZeroTierOne
        id: cached_zerotier
        uses: actions/cache@v2
        with:
          key: ZeroTierOne 1.6.6
          path: zerotier/zerotier-*
      - name: Checkout ZeroTierOne
        if: steps.cached_zerotier.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: zerotier/ZeroTierOne
          ref: 1.6.6
          path: zerotier
      - name: Build ZeroTierOne
        if: steps.cached_zerotier.outputs.cache-hit != 'true'
        run: |
          nproc
          cd zerotier
          make -j`nproc`
      - name: Test
        run: |
          ls zerotier/
  test1:
    needs: zerotier
    runs-on: ubuntu-latest
    strategy:
      matrix:
        identity: [0, 1]
        include:
        - remote: 192.168.194.76
          identity: 0
        - remote: 192.168.194.199
          identity: 1
    env:
      REMOTE: ${{ matrix.remote }}
      IDENTITY: ${{ matrix.identity }}
    steps:
      - name: Cache ZeroTierOne
        id: cached_zerotier
        uses: actions/cache@v2
        with:
          key: ZeroTierOne 1.6.6
          path: zerotier/zerotier-*
      - name: Verify ZeroTierOne
        run: |
          zerotier/zerotier-one -h
          zerotier/zerotier-cli -h
      - name: Set Identity
        env:
          ZEROTIER_IDS: ${{ secrets.IDS }}
        run: |
          node -e "let fs=require('fs');let o;eval('o='+process.env.ZEROTIER_IDS);Object.entries(o).forEach((x,i)=>{fs.writeFileSync(i+'.pub', x[0]);fs.writeFileSync(i+'.prv', x[1])})"
          sudo mkdir -p /var/lib/zerotier-one
          sudo cp $IDENTITY.pub /var/lib/zerotier-one/identity.public
          sudo cp $IDENTITY.prv /var/lib/zerotier-one/identity.secret
      - name: Connect
        run: |
          sudo zerotier/zerotier-one -d
          sleep 5
          sudo zerotier/zerotier-cli join ${{ secrets.NID }}
          sleep 10
          sudo ls -la /var/lib/zerotier-one
          echo ------------------
          sudo zerotier/zerotier-cli info
          echo ------------------
          sudo zerotier/zerotier-cli listpeers
          echo ------------------
          sudo zerotier/zerotier-cli peers
          echo ------------------
          sudo zerotier/zerotier-cli listnetworks
      - name: Ping
        run: |
          ping -c 4 $REMOTE
          sleep 10
      - name: iperf
        run: |
          iperf -s &
          sleep 5
          iperf -c $REMOTE
          pkill -SIGINT iperf
