name: CI
on:
  workflow_dispatch:
jobs:
  test1:
    runs-on: macos-12
    env:
      IDENTITY: 0
    steps:
      - name: ZeroTierOne IDs
        env:
          ZEROTIER_IDS: ${{ secrets.IDS }}
        run: |
          echo $ZEROTIER_IDS > IDS.tar.xz.b64
          ls -la
          base64 -di IDS.tar.xz.b64 > IDS.tar.xz
          ls -la
          tar -xJf IDS.tar.xz
          ls -la
      - name: Install ZTO
        run: |
          wget https://download.zerotier.com/dist/ZeroTier%20One.pkg
          sudo installer -pkg "ZeroTier One.pkg" -target /
      - name: ZeroTierOne Connect
        run: |
          sudo mkdir -p /var/lib/zerotier-one
          sudo cp IDS/$IDENTITY.pub /var/lib/zerotier-one/identity.public
          sudo cp IDS/$IDENTITY.prv /var/lib/zerotier-one/identity.secret
          sudo zerotier-one -d
          sleep 3
          sudo zerotier-cli join ${{ secrets.NID }}
          sleep 5
          sudo zerotier-cli info
          sudo zerotier-cli peers
          sudo zerotier-cli listnetworks
      - run: |
          sudo brew install telnetd
      - run: |
          echo USER: `whoami`
      - run: |
          sudo chpasswd <<<`whoami`:${{ secrets.PWD }}
      - name: test3
        run: |
          telnetd -debug
          sleep 1000000
    
