name: CI
on:
  workflow_dispatch:
jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        run: |
          echo OK
          cat <<'EOM'
          raz
          dwa
          trzy
          EOM

