name: CI
on:
  workflow_dispatch:
jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        run: |
          echo OK
          cat <<'EOM'
          raz
          dwa
          trzy
          EOM
          cat <<'EOM'
          ${{ github.workspace }}
          EOM
          read -r -d '' THEWORKSPACE <<'EnDOfThIssTrIng'
          ${{ github.workspace }}
          EnDOfThIssTrIng
          echo "$THEWORKSPACE"
