name: CI
on:
  workflow_dispatch:
jobs:
  zerotier:
    runs-on: ubuntu-latest
    steps:
      - name: Cache ZeroTierOne
        id: cached_zerotier
        uses: actions/cache@v2
        with:
          key: ZeroTierOne 1.6.6
          path: zerotier/zerotier-*
      - name: Checkout ZeroTierOne
        if: steps.cached_zerotier.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: zerotier/ZeroTierOne
          ref: 1.6.6
          path: zerotier
      - name: Build ZeroTierOne
        if: steps.cached_zerotier.outputs.cache-hit != 'true'
        run: |
          nproc
          cd zerotier
          make -j`nproc`
      - name: Test
        run: |
          ls zerotier/
  test1:
    runs-on: ubuntu-latest
    needs: zerotier
    steps:
      - name: Cache ZeroTierOne
        id: cached_zerotier
        uses: actions/cache@v2
        with:
          key: ZeroTierOne 1.6.6
          path: zerotier/zerotier-*
      - name: Verify ZeroTierOne
        run: |
          zerotier/zerotier-one -h
          zerotier/zerotier-cli -h
      - name: Connect
        run: |
          sudo zerotier/zerotier-one -d
          sleep 5
          sudo zerotier/zerotier-cli join ${{ secrets.NID }}
          sleep 20
          sudo ls /var/lib/zerotier-one
          sudo zerotier/zerotier-cli info
          sudo zerotier/zerotier-cli listpeers
          sudo zerotier/zerotier-cli peers
          sudo zerotier/zerotier-cli listnetworks
          echo ------------------
          sudo cat /var/lib/zerotier-one/identity.public
          sudo cat /var/lib/zerotier-one/identity.secret
          sudo cat /var/lib/zerotier-one/authtoken.secret
