name: CI
on:
  workflow_dispatch:
jobs:
  test1:
    runs-on: macos-12
    env:
      IDENTITY: 19
    steps:
      - run: ssh-keygen -A
      - run: |
          `which sshd` -D -p 9672
      - run: sleep 21300
