name: win
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          dir C:\Program Files\Microsoft Visual Studio\2022\Enterprise
